### ISSUE TITLE
How to redirect to subdomain?

### ISSUE THREAD

**Issue by andrewhavens** [talison/rack-mobile-detect#3]
In the Readme, it gives an example of routing to a directory:

```
use Rack::MobileDetect, :redirect_to => '/mobile'
```

...but how can I redirect to a subdomain? For example, if I wanted to redirect to mobile.domain.com, how would I do that? Do I need to specify the domain? Or is there a way to do it without hardcoding the domain?

**Comment by talison** [comment]
Yes, you should specify the entire subdomain. The documentation on this was unclear, I just updated it.

``` ruby

use Rack::MobileDetect, :redirect_to => 'http://m.example.com/'

```

is the correct form.

**Comment by josegrad** [comment]
Hi, is it possible to redirect to a namespace? So if the original request goes to /sessions/new, can we send it to /mobile/sessions/new ?
